import * as React from 'react'
import Nav from './Nav'
import Head from 'next/head'
import Image from 'next/image'
import dashboard from '../public/images/dashboard/3dcube.png';
import learning from '../public/images/dashboard/book.png';
import resource from '../public/images/dashboard/resources.png';
import profile from '../public/images/dashboard/frame.png';
import community from '../public/images/dashboard/people.png';
import message from '../public/images/dashboard/sms.png';
import completed from '../public/images/dashboard/Checkbox.png';
import communities from '../public/images/dashboard/communities.png';
import progress from '../public/images/dashboard/course.png';
import calender from '../public/images/dashboard/calendar.png';
import clock from '../public/images/dashboard/clock.png';
import strength from '../public/images/dashboard/strength.png';
import learn from '../public/images/dashboard/learn.png';
import time from '../public/images/dashboard/time.png';
import learnings from '../public/images/dashboard/learning.png';
import left from '../public/images/dashboard/left.png';
import right from '../public/images/dashboard/right.png';
import image1 from '../public/images/dashboard/image 1.png';
import image2 from '../public/images/dashboard/image 2.png';
import image3 from '../public/images/dashboard/image 3.png';
import love from '../public/images/dashboard/Vector.png';
import logo from '../public/images/landingPage/nav-logo.png';
import styles from '../styles/Dashboard.module.scss'
import Link from 'next/link';

let token: any;
if (typeof window !== "undefined") {
    token = localStorage.getItem("token");
}

const SideNav: React.FC = () => {
    
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <Link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossOrigin="anonymous"></link>
            </Head>
            <div className="container-fluid">
                <div className={styles.sidebar}>
                    <ul className="navbar-nav">
                            <li>
                                <Link href="/dashboard" className='text-decoration-none'>
                                    <Image src={dashboard} alt="Dashboard" />
                                    <span>Dashboard</span>
                                </Link>
                            </li>
                            <li>
                                <Link href="" className='text-decoration-none'>
                                    <Image src={learning} alt="Learning Hub" />
                                    <span>Learning Hub</span>
                                </Link>
                            </li>
                            <li>
                                <Link href="" className='text-decoration-none'>
                                    <Image src={resource} alt="Resource Hub" />
                                    <span>Resource Hub</span>
                                </Link>
                            </li>
                            <li>
                                <Link href="/profile" className='text-decoration-none'>
                                    <Image src={profile} alt="Profile" />
                                    <span>Profile</span>
                                </Link>
                            </li>
                            <li>
                                <Link href="" className='text-decoration-none'>
                                    <Image src={community} alt="Communities" />
                                    <span>Communities</span>
                                </Link>
                            </li>
                            <li>
                                <Link href="" className='text-decoration-none'>
                                    <Image src={message} alt="Messages" />
                                    <span>Messages</span>
                                </Link>
                            </li>
                    </ul>
                </div>
                <div className={styles.sidebars}>
                    <nav className="navbar navbar-expand-lg bg-body-large">
                        <div className="container-fluid mx-auto">
                            <Link className="navbar-brand" href="/">
                                <div className="col-2 d-flex">
                                    <Image src={logo} width={30} alt='logo' />
                                    <span>Venture</span>
                                </div>
                            </Link>
                            <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <span className="navbar-toggler-icon"></span>
                            </button>
                            <div className="collapse navbar-collapse justify-content-center justify-content-md-end" id="navbarSupportedContent">
                                <ul className="navbar-nav">
                                    <li>
                                        <Link href="/dashboard" className='text-decoration-none'>
                                            <Image src={dashboard} alt="Dashboard" />
                                            <span>Dashboard</span>
                                        </Link>
                                    </li>
                                    <li>
                                        <Link href="" className='text-decoration-none'>
                                            <Image src={learning} alt="Learning Hub" />
                                            <span>Learning Hub</span>
                                        </Link>
                                    </li>
                                    <li>
                                        <Link href="" className='text-decoration-none'>
                                            <Image src={resource} alt="Resource Hub" />
                                            <span>Resource Hub</span>
                                        </Link>
                                    </li>
                                    <li>
                                        <Link href="/profile" className='text-decoration-none'>
                                            <Image src={profile} alt="Profile" />
                                            <span>Profile</span>
                                        </Link>
                                    </li>
                                    <li>
                                        <Link href="" className='text-decoration-none'>
                                            <Image src={community} alt="Communities" />
                                            <span>Communities</span>
                                        </Link>
                                    </li>
                                    <li>
                                        <Link href="" className='text-decoration-none'>
                                            <Image src={message} alt="Messages" />
                                            <span>Messages</span>
                                        </Link>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </nav>
                </div>
                {/* <div className={styles.section}>
                </div> */}
            </div>
        </>
    )
}
export default SideNav;