import * as React from 'react'
import Head from "next/head";
import Image from 'next/image'
import { useState } from "react";
import linkedIn from '../../public/images/dashboard/linkedln.png';
import facebook from '../../public/images/dashboard/facebook.png';
import twitter from '../../public/images/dashboard/twitter.png';
import instagram from '../../public/images/dashboard/instagram.png';
import share from '../../public/images/dashboard/share.png';
import styles from '../../styles/EditVenture.module.scss';
import { fetchUser } from '../features/users/userSlice';
import { useAppDispatch, useAppSelector } from '../hooks';
import Link from 'next/link';
import Nav from '../../components/Nav';
import axios, { AxiosResponse } from 'axios';

interface FormValues {
    name: string;
    dob: string;
    bio: string;
    skills: string[];
    phone: string;
    nationality: string;
    gender: string;
}

let email:any;
let token:any;
if (typeof window !== "undefined") {
    email = localStorage.getItem('email');
    token = localStorage.getItem('token');
}

const AddVentures: React.FC = () => {
    const [isLoading, setIsLoading] = useState(false);
    const [errors, setErrors] = useState<any>([]);
    const dispatch = useAppDispatch();
    const user = useAppSelector(state => state.user.users);
    React.useEffect(() => {
        dispatch(fetchUser())
    }, [])
    const [formValues, setFormValues] = useState<FormValues>({
        name: user.name,
        dob: user.dob,
        bio: user.bio,
        skills: user.skills,
        phone: user.phone,
        nationality: user.nationality,
        gender: user.gender,
    });
    const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {     
        const { name, value } = event.target;
        setFormValues((prevValues) => ({
            ...prevValues,
            [name]: value,
        }));
    };
    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true);
        console.log(formValues);
        axios.patch(`https://api.venturenation.co/api/v1/users/${email}`, formValues, {
            headers: {
                Authorization: `Bearer ${token}`,
            }}
        ).then((response: AxiosResponse) => {
            console.log(response.data);
        })
        .catch((error) => {
            setErrors(error.message);
            setIsLoading(false);
        })
        .finally(() => {
            setIsLoading(false);
        })
    }
    if (!user) {
        return <div>Loading...</div>; // Display loading indicator while fetching user data
    }
    return (
        <>
            <Head>
                <title>Add venture</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
                crossOrigin="anonymous"
                ></link>
            </Head>
            <div className="container-fluid">
                <Nav />
                <div className={styles.section}>
                    <div className="row px-5 justify-content-between">
                        <div className="col-5">
                            <p><i className="fa fa-arrow-left" aria-hidden="true"></i>Back to profile</p>
                            <h2>Add a new venture</h2>
                            <div className='fs-5' style={{
                                color: '#7E848E'
                            }}>
                                Create a new venture profile that tells the world about what you do to impact it. Share your data and information to gain access to a pool of resources, tools, perks, and services tailored just for you. Open yourself up to investment opportunities.
                            </div>
                        </div>
                        <div className="col-7 ps-4">
                            <div className="col-11">
                                <form onSubmit={handleSubmit}>                                       
                                        <div className="row justify-content-center mb-4">
                                            <div className="form-group col-6">
                                                <label className="form-label" htmlFor="phone">Venture name <i className="fa fa-asterisk" aria-hidden="true" style={{color: "red"}}></i> </label>
                                                <input type="text" className="form-control" name="phone" id="phone" placeholder="+234 908 745 3451" value='' onChange={handleInputChange} />
                                            </div>
                                            <div className="form-group col-6">
                                                <label htmlFor="nationality" className="form-label">Date founded <i className="fa fa-asterisk" aria-hidden="true" style={{color: "red"}}></i> </label>
                                                <input type="date" className="form-control" name="nationality" id="nationality" placeholder="" value='' onChange={handleInputChange} />
                                            </div>
                                        </div>
                                        <div className="form-group mb-4">
                                            <label className="form-label" htmlFor="name">Venture tagline</label>
                                            <input type="text" className="form-control" name="name" id="name" placeholder="Full name" value='' onChange={handleInputChange} />
                                        </div>
                                        <div className="row justify-content-center mb-4">
                                            <div className="form-group col-6">
                                                <label className="form-label" htmlFor="phone">Stage <i className="fa fa-asterisk" aria-hidden="true" style={{color: "red"}}></i> </label>
                                                <input type="text" className="form-control" name="phone" id="phone" placeholder="+234 908 745 3451" value='' onChange={handleInputChange} />
                                            </div>
                                            <div className="form-group col-6">
                                                <label htmlFor="nationality" className="form-label">Location <i className="fa fa-asterisk" aria-hidden="true" style={{color: "red"}}></i> </label>
                                                <input type="text" className="form-control" name="nationality" id="nationality" placeholder="City, Country" value='' onChange={handleInputChange} />
                                            </div>
                                        </div>
                                        <h4 className='py-3'>Overview</h4>
                                        <div className="row justify-content-center mb-4">
                                            <div className="form-group col-6">
                                                <label className="form-label" htmlFor="phone">Sector <i className="fa fa-asterisk" aria-hidden="true" style={{color: "red"}}></i> </label>
                                                <input type="text" className="form-control" name="phone" id="phone" placeholder="+234 908 745 3451" value='' onChange={handleInputChange} />
                                            </div>
                                            <div className="form-group col-6">
                                                <label htmlFor="nationality" className="form-label">Customer model <i className="fa fa-asterisk" aria-hidden="true" style={{color: "red"}}></i> </label>
                                                <input type="text" className="form-control" name="nationality" id="nationality" placeholder="City, Country" value='' onChange={handleInputChange} />
                                            </div>
                                        </div>
                                        <div className="form-group mb-4">
                                            <label className="form-label" htmlFor="name">Description <i className="fa fa-asterisk" aria-hidden="true" style={{color: "red"}}></i> </label>
                                            <input type="text" className="form-control" name="name" id="name" placeholder="Full name" value='' onChange={handleInputChange} />
                                        </div>
                                        <div className="form-group mb-4">
                                            <label className="form-label" htmlFor="name">Link (website or your pitch deck) <i className="fa fa-asterisk" aria-hidden="true" style={{color: "red"}}></i> </label>
                                            <input type="text" className="form-control" name="name" id="name" placeholder="Full name" value='' onChange={handleInputChange} />
                                        </div>
                                        <h4 className='py-3'>Social profiles</h4>
                                        <div className="row justify-content-center">
                                            <div className="form-group col-md-6 col-sm-10">
                                                <label className="form-label" htmlFor="linkedin">LinkedIn profile link</label>
                                                <input type="text" className="form-control ps-5" name="linkedin" id="linkedin" placeholder="https://" value='' onChange={handleInputChange} />
                                                <Image src={linkedIn} alt='linkedIn logo' className={styles.icons}/>
                                            </div>
                                            <div className="form-group col-md-6 col-sm-10">
                                                <label htmlFor="twitter" className="form-label">Twitter profile link</label>
                                                <input type="text" className="form-control ps-5" name="twitter" id="twitter" placeholder="https://" value='' onChange={handleInputChange} />
                                                <Image src={twitter} alt='twitter logo' className={styles.icons}/>
                                            </div>
                                        </div>
                                        <div className="row justify-content-center">
                                            <div className="form-group col-md-6 col-sm-10">
                                                <label className="form-label" htmlFor="instagram">Instagram profile link</label>
                                                <input type="text" className="form-control ps-5" name="instagram" id="instagram" placeholder="https://" value='' onChange={handleInputChange} />
                                                <Image src={instagram} alt='instagram logo' className={styles.icons}/>
                                            </div>
                                            <div className="form-group col-md-6 col-sm-10">
                                                <label htmlFor="facebook" className="form-label">Facebook profile link</label>
                                                <input type="text" className="form-control ps-5" name="facebook" id="facebook" placeholder="https://" value='' onChange={handleInputChange} />
                                                <Image src={facebook} alt='facebook logo' className={styles.icons}/>
                                            </div>
                                        </div>
                                        <div>
                                            <button type="submit" className={styles.signup} disabled={isLoading} >{isLoading ? "Updating..." : "Update"}</button>
                                        </div>
                                    </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
export default AddVentures;