import * as React from 'react'
import Nav from '../components/Nav'
import Head from 'next/head'
import Image from 'next/image'
import dashboard from '../public/images/dashboard/3dcube.png';
import learning from '../public/images/dashboard/book.png';
import resource from '../public/images/dashboard/resources.png';
import profile from '../public/images/dashboard/frame.png';
import community from '../public/images/dashboard/people.png';
import message from '../public/images/dashboard/sms.png';
import completed from '../public/images/dashboard/Checkbox.png';
import communities from '../public/images/dashboard/communities.png';
import progress from '../public/images/dashboard/course.png';
import calender from '../public/images/dashboard/calendar.png';
import clock from '../public/images/dashboard/clock.png';
import strength from '../public/images/dashboard/strength.png';
import learn from '../public/images/dashboard/learn.png';
import time from '../public/images/dashboard/time.png';
import learnings from '../public/images/dashboard/learning.png';
import left from '../public/images/dashboard/left.png';
import right from '../public/images/dashboard/right.png';
import image1 from '../public/images/dashboard/image 1.png';
import image2 from '../public/images/dashboard/image 2.png';
import image3 from '../public/images/dashboard/image 3.png';
import love from '../public/images/dashboard/Vector.png';
import logo from '../public/images/landingPage/nav-logo.png';
import styles from '../styles/Dashboard.module.scss'
import Link from 'next/link';
import { GetServerSideProps } from 'next';
import axios from 'axios';
import SideNav from '../components/SideNav';

let token: any;
if (typeof window !== "undefined") {
    token = localStorage.getItem("token");
}

const AddPost: React.FC = () => {
    const [data, setData] = React.useState<any>(null);

    React.useEffect(() => {
        fetch("http://localhost:5000/user/dashboard", {
        headers: {
            Authorization: `Bearer ${token}`,
        },
        })
        .then((res) => res.json())
        .then((data) => {
            setData(data);
            localStorage.setItem('email', data.email);
        });
    }, []);
    
    return (
        <>
            <Head>
                <title>Dashboard</title>
                <meta name="description" content="Generated by create next app" />
                <Link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossOrigin="anonymous"></link>
            </Head>
            <div className="container-fluid">
                <Nav />
                <SideNav />
                <div className={styles.section}>
                    <div className="row">
                        <div className="col-lg-8 mb-4">
                            <div className={styles.section__info}>
                                <div className="p-2">
                                    <div className={styles.section__info__header}>
                                        <div className="row">
                                            <div className="col-4">
                                                <div className="d-flex shadow-sm px-3 pt-3">
                                                    <div className="">
                                                        <Image src= {completed} alt=""/>
                                                    </div>
                                                    <div className="">
                                                        <h5>Completed</h5>
                                                        <p className='course'>27</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-4">
                                                <div className="d-flex shadow-sm ps-2 pt-3">
                                                    <div className="">
                                                        <Image src= {progress} alt=""/>
                                                    </div>
                                                    <div className="">
                                                        <h5>Course in Progress</h5>
                                                        <p className='course'>27</p>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-4">
                                                <div className="d-flex shadow-sm ps-2 pt-3">
                                                    <div className="">
                                                        <Image src= {communities} alt=""/>
                                                    </div>
                                                    <div className="">
                                                        <h5>Total Communities</h5>
                                                        <p className='course'>27</p>
                                                    </div>
                                                </div>                                  
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <div className="shadow-sm mt-lg-3 mt-sm-2">
                                    <div className={styles.section__info__body}>
                                        <div className={styles.section__info__body__header}>
                                            <div className="d-flex justify-content-between">
                                                <h5>Course in Progress</h5>
                                                <div className="d-flex">
                                                    <Image src={right} alt='Arrow Left' />
                                                    <Image src={left} alt='Arrow Right' />
                                                </div>
                                            </div>
                                        </div>
                                        <div className="row ps-3 justify-content-around">
                                            <div className="col-md-3 col-sm-5 border-0 shadow-sm p-0">
                                                <Image src={learn} className="card-img-top" alt="..." />
                                                <div className="card-body">
                                                    <h6 className="card-title pt-3">Understanding your target customers. </h6>
                                                    <p className="card-text">Venture Nation.</p>
                                                    <div className="d-flex justify-content-between">
                                                        <Image src={strength} alt="Progress bar" width={130} height={3} />
                                                        <p className={styles.per}>37%</p>
                                                    </div>
                                                    <a href="#" className='text-decoration-none float-end'>Rate this course</a>
                                                </div>
                                            </div>
                                            <div className="col-md-3 col-sm-5 border-0 shadow-sm p-0">
                                                <Image src={time} className="card-img-top" alt="..." />
                                                <div className="card-body">
                                                    <h6 className="card-title pt-3">Understanding your target customers. </h6>
                                                    <p className="card-text">Venture Nation.</p>
                                                    <div className="d-flex justify-content-between">
                                                        <Image src={strength} alt="Progress bar" width={130} height={3} />
                                                        <p className={styles.per}>37%</p>
                                                    </div>
                                                    <a href="#" className='text-decoration-none float-end'>Rate this course</a>
                                                </div>
                                            </div>
                                            <div className="col-md-3 col-sm-5 border-0 shadow-sm p-0">
                                                <Image src={learnings} className="card-img-top" alt="..." />
                                                <div className="card-body">
                                                    <h6 className="card-title pt-3">Understanding your target customers. </h6>
                                                    <p className="card-text">Venture Nation.</p>
                                                    <div className="d-flex justify-content-between">
                                                        <Image src={strength} alt="Progress bar" width={130} height={3}/>
                                                        <p className={styles.per}>57%</p>
                                                    </div>
                                                    <a href="#" className='text-decoration-none float-end'>Rate this course</a>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div> 
                                <div className="shadow-sm mt-lg-5 mt-sm-3">
                                    <div className={styles.section__info__end}>
                                        <div className={styles.section__info__end__header}>
                                            <div className="d-flex justify-content-between">
                                                <h5>Recommended Course</h5>
                                                <div className="d-flex">
                                                    <Image src={right} alt='Arrow Left' />
                                                    <Image src={left} alt='Arrow Right' />
                                                </div>
                                            </div>
                                        </div>
                                        <div className="row justify-content-around">
                                            <div className="col-sm-3 border-0 shadow-sm p-0">
                                                <Image src={image1} className="card-img-top" alt="..." />
                                                <div className="card-body">
                                                    <h6 className="card-title pt-3">Understanding your target customers. </h6>
                                                    <p className="card-text">Venture Nation.</p>
                                                    <div className="d-flex justify-content-between">
                                                        <div className="d-flex">
                                                            <Image src={calender} alt="Calender" />
                                                            <p>8 Lessons</p>
                                                        </div>
                                                        <div className="d-flex">
                                                            <Image src={clock} alt="Clock" />
                                                            <p>18 Hours</p>
                                                        </div>
                                                    </div>
                                                    <div className="d-flex justify-content-between">
                                                        <p className=''>Free</p>
                                                        <Image src={love} alt='Favorite icon' />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-sm-3 border-0 shadow-sm p-0">
                                                <Image src={image2} className="card-img-top" alt="..." />
                                                <div className="card-body">
                                                    <h6 className="card-title pt-3">Understanding your target customers. </h6>
                                                    <p className="card-text">Venture Nation.</p>
                                                    <div className="d-flex justify-content-between">
                                                        <div className="d-flex">
                                                            <Image src={calender} alt="Calender" />
                                                            <p>8 Lessons</p>
                                                        </div>
                                                        <div className="d-flex">
                                                            <Image src={clock} alt="Clock" />
                                                            <p>18 Hours</p>
                                                        </div>
                                                    </div>
                                                    <div className="d-flex justify-content-between">
                                                        <p className=''>Free</p>
                                                        <Image src={love} alt='Favorite icon' />
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-sm-3 border-0 shadow-sm p-0">
                                                <Image src={image3} className="card-img-top" alt="..." />
                                                <div className="card-body">
                                                    <h6 className="card-title pt-3">Understanding your target customers. </h6>
                                                    <p className="card-text">Venture Nation.</p>
                                                    <div className="d-flex justify-content-between">
                                                        <div className="d-flex">
                                                            <Image src={calender} alt="Calender" />
                                                            <p>8 Lessons</p>
                                                        </div>
                                                        <div className="d-flex">
                                                            <Image src={clock} alt="Clock" />
                                                            <p>18 Hours</p>
                                                        </div>
                                                    </div>
                                                    <div className="d-flex justify-content-between">
                                                        <p className=''>Free</p>
                                                        <Image src={love} alt='Favorite icon' />
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-4">
                            <div className="shadow-sm px-3">
                                <div className={styles.section__session}>
                                    <div className={styles.section__session__header}>
                                        <h5>Upcoming sessions</h5>
                                    </div>
                                    <div className={styles.section__session__body}>
                                        <div className="p-2 shadow-sm px-4">
                                            <h6>Mentorship with <span>Gilda Charles</span></h6>
                                            <div className="d-flex justify-content-between">
                                                <div className="d-flex">
                                                    <Image src={calender} alt='calender'/>
                                                    <p>Wed, Jun 28</p>
                                                </div>
                                                <div className="d-flex">
                                                    <Image src={clock} alt='clock'/>
                                                    <p>3:00 pm WAT</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="p-2 shadow-sm px-4">
                                            <h6>Mentorship with <span>James Mary</span></h6>
                                            <div className="d-flex justify-content-between">
                                                <div className="d-flex">
                                                    <Image src={calender} alt='calender'/>
                                                    <p>Wed, Jun 28</p>
                                                </div>
                                                <div className="d-flex">
                                                    <Image src={clock} alt='clock'/>
                                                    <p>3:00 pm WAT</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="p-2 shadow-sm px-4">
                                            <h6>Mentorship with <span>Travis Crosby</span></h6>
                                            <div className="d-flex justify-content-between">
                                                <div className="d-flex">
                                                    <Image src={calender} alt='calender'/>
                                                    <p>Wed, Jun 28</p>
                                                </div>
                                                <div className="d-flex">
                                                    <Image src={clock} alt='clock'/>
                                                    <p>3:00 pm WAT</p>
                                                </div>
                                            </div>
                                        </div>
                                        <div className={styles.btn}>
                                            <button className="btn">View all Coaching Sessions</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )

}
export default AddPost;