import * as React from 'react'
import Nav from '../components/Nav'
import Head from 'next/head'
import Image from 'next/image'
import profile from '../public/images/dashboard/frame.png';
import image1 from '../public/images/dashboard/image 1.png';
import image2 from '../public/images/dashboard/image 2.png';
import axios, { AxiosResponse } from "axios";
import styles from '../styles/Dashboard.module.scss'
import Link from 'next/link';
import SideNav from '../components/SideNav';
import linkedln from '../public/images/dashboard/linkedln.png';
import facebook from '../public/images/dashboard/facebook.png';
import twitter from '../public/images/dashboard/twitter.png';
import instagram from '../public/images/dashboard/instagram.png';
import share from '../public/images/dashboard/share.png';
import phone from '../public/images/dashboard/call.png';
import website from '../public/images/dashboard/web.png';
import mail from '../public/images/dashboard/mail.png';
import edit from '../public/images/dashboard/edit.png';
import add from '../public/images/dashboard/add.png';
import location from '../public/images/dashboard/location.png'
import date from '../public/images/dashboard/date.png';
import gender from '../public/images/dashboard/gender.png';
import location2 from '../public/images/dashboard/location2.png'
import team from '../public/images/dashboard/team.png';
import company from '../public/images/dashboard/company.png';
import company2 from '../public/images/dashboard/company2.png'

// let token: any;
let email:any;
if (typeof window !== "undefined") {
    // token = localStorage.getItem("token");
    email = localStorage.getItem('email');
}

const Profile: React.FC = () => {
    const [user, setUser] = React.useState<any>('');
    React.useEffect(() => {
        axios.get(`https://api.venturenation.co/api/v1/users/${email}`)
        .then((response: AxiosResponse) => {
            setUser(response.data.data);
        })
    }, []);
    console.log(user);
    
    
    return (
        <>
            <Head>
                <title>Profile</title>
                <meta name="description" content="Generated by create next app" />
                <Link rel="icon" href="/favicon.ico" />
                <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM" crossOrigin="anonymous"></link>
            </Head>
            <div className="container-fluid">
                <Nav />
                <SideNav />
                <div className={styles.section}>
                    <div className="row">
                        <div className="col-lg-9 mb-4">
                            <div className={styles.section__info}>
                                <div className="p-2">
                                    <div className={styles.section__info__profile}>
                                        <div className=''>
                                            {/* eslint-disable-next-line @next/next/no-img-element */}
                                            <img src={user.avatar} alt="Profile Image" className={styles.section__info__profile__image}/>
                                        </div>
                                    </div>
                                </div> 
                                <div className="float-end">
                                    <div className={styles.section__info__text}>
                                        <Image src={edit} alt='share icon' className='me-2'/>
                                        <Link href='/editProfile' className='text-decoration-none'>Edit Profile</Link>
                                    </div>
                                </div>
                                <div className="px-4 pt-4">
                                    <br />
                                    <h5 className="">{user.name}</h5>
                                    <p className="">{user.email}</p>
                                    {user.bio && <p className="">{user.bio}</p>}
                                    <div className="d-flex">
                                        <div className="d-flex me-4">
                                            <Image src={location} alt="location icon" className='mt-2' />
                                            {user.nationality ? <p className='pt-1'>{user.nationality}</p> : <p className='pt-1'>Lagos, Nigeria</p>}
                                        </div>
                                        <div className="d-flex me-4">
                                            <Image src={date} alt="date icon" className='mt-2' />
                                            {user.date ? <p className='pt-1'>{user.dob}</p> : <p className='pt-1'>March 12, 1995</p>}
                                        </div>
                                        <div className="d-flex">
                                            <Image src={gender} alt="gender icon" className='mt-2' />
                                            {user.gender ? <p className='pt-1'>{user.gender}</p> : <p className='pt-1'>Male</p>}
                                        </div>
                                    </div>
                                    <div className="row">
                                        <h4>Skills</h4>
                                        <div className="d-flex">
                                            <p className={styles.skills}>
                                                Learning
                                            </p>
                                            <p className={styles.skills}>
                                                Communication
                                            </p>
                                            <p className={styles.skills}>
                                                Critical thinking
                                            </p>
                                        </div>
                                    </div>
                                </div>
                                <div className="mt-lg-5 mt-sm-3">
                                    <div className={styles.section__info__end}>
                                        <div className={styles.section__info__end__header}>
                                            <div className="d-flex justify-content-between">
                                                <h5>My Ventures</h5>
                                                <div className="float-end">
                                                    <div className={styles.section__info__text}>
                                                        <Image src={add} alt='share icon' className='me-2'/>
                                                        Add Ventures
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div className="row justify-content-between px-4">
                                            <div className="col-5 border-0 shadow-sm p-0">
                                                <Image src={image2} alt='venture banner' className={styles.section__info__end__venture} />
                                                <Image src={company} alt='venture logo' className={styles.section__info__end__venture__logo}/>
                                                <h4 className={styles.venture__text}>Venture Name</h4>
                                                <p className={styles.venture__text__p}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illum, eos ex dolor accusamus eaque omnis</p>
                                                <div className={styles.icons}>
                                                    <div className="d-flex me-4">
                                                        <Image src={location2} alt='location icon' className='mt-2'/>
                                                        {user.location ? <p className='pt-1'>{user.location}</p> : <p className='pt-1'>Lagos, Nigeria</p>}
                                                    </div>
                                                    <div className="d-flex">
                                                        <Image src={team} alt='team icon' className='mt-2'/> <span className='pt-1'>18 Team members</span>
                                                    </div>
                                                </div>
                                            </div>
                                            <div className="col-5 border-0 shadow-sm p-0">
                                                <Image src={image1} alt='venture banner' className={styles.section__info__end__venture} />
                                                <Image src={company2} alt='venture logo' className={styles.section__info__end__venture__logo}/>
                                                <h4 className={styles.venture__text}>Venture Name</h4>
                                                <p className={styles.venture__text__p}>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Illum, eos ex dolor accusamus eaque omnis</p>
                                                <div className={styles.icons}>
                                                    <div className="d-flex me-4">
                                                        <Image src={location2} alt='location icon' className='mt-2'/>
                                                        {user.location ? <p className='pt-1'>{user.location}</p> : <p className='pt-1'>Lagos, Nigeria</p>}
                                                    </div>
                                                    <div className="d-flex">
                                                        <Image src={team} alt='team icon' className='mt-2'/> <span className='pt-1'>18 Team members</span>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div> 
                                </div>
                            </div>
                        </div>
                        <div className="col-lg-3">
                            <div className="shadow-sm px-3">
                                <div className=''>
                                    <div className={styles.section__session__header}>
                                        <h5>Contact Info</h5>
                                    </div>
                                    <div className={styles.section__session__body}>
                                        <div className="p-2 px-4">
                                            <Image src={phone} alt='phone icon'/> <span className='text-dark'>Phone</span>
                                            <div className="d-flex justify-content-between">
                                                <p className='ps-2'> {user.phone ? user.phone : '(+234) 809 000 0000'} </p>
                                            </div>
                                        </div>
                                        <div className="p-2 px-4">
                                            <Image src={website} alt='phone icon'/> <span className='text-dark'>Website</span>
                                            <div className="d-flex justify-content-between">
                                                <p> {user.website ? user.website : 'samplewebsite.com'} </p>
                                            </div>
                                        </div>
                                        <div className="p-2 px-4 mb-3">
                                            <Image src={mail} alt='phone icon'/> <span className='text-dark'>Email address</span>
                                            <div className="d-flex justify-content-between">
                                                <p> {user.email} </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div className="px-3 mt-5">
                                <div className={styles.section__end}>
                                    <div className={styles.section__session__header}>
                                        <h5>Socials</h5>
                                    </div>
                                        <div className={styles.section__session__body}>
                                            <div className="px-3 shadow-sm">
                                                <div className="d-flex pb-4">
                                                    <Image src={linkedln} alt='Linkedln icon'/>
                                                    <div className='ps-2'>
                                                        <p className='mb-0'>Linkedln</p>
                                                        <Link href='{user.linkedln}'>view likened profile</Link> <Image src={share} alt='share icon'/>
                                                    </div>
                                                </div>
                                                <div className="d-flex pb-4">
                                                    <Image src={twitter} alt='Twitter icon'/>                                               
                                                    <div className='ps-2'>
                                                        <p className='mb-0'>Twitter</p>
                                                        <Link href='{user.twitter}'>view twitter profile</Link> <Image src={share} alt='share icon'/>
                                                    </div>
                                                </div>
                                                <div className="d-flex pb-4">
                                                    <Image src={instagram} alt='Instagram icon'/>
                                                    <div className='ps-2'>
                                                        <p className='mb-0'>Instagram</p>
                                                        <Link href='{user.instagram}'>view instagram profile</Link> <Image src={share} alt='share icon'/>
                                                    </div>
                                                </div>
                                                <div className="d-flex pb-4">
                                                    <Image src={facebook} alt='Facebook icon'/>
                                                    <div className='ps-2'>
                                                        <p className='mb-0'>Facebook</p>
                                                        <Link href='{user.facebook}'>view facebook profile</Link> <Image src={share} alt='share icon'/>
                                                    </div>
                                                </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )

}
export default Profile;