import * as React from 'react'
import Head from "next/head";
import styles from '../styles/Signup.module.scss';
import Image from 'next/image'
import { useState } from "react";
import logo from '../public/images/landingPage/nav-logo.png';
import eye from '../public/images/landingPage/Icon.png';
import strength from '../public/images/landingPage/strength.png';
import strong from '../public/images/landingPage/strong.png';
import images from '../public/images/landingPage/1.png'
import Link from 'next/link';
import axios, { AxiosResponse } from 'axios';
import * as yup from 'yup';
import { useRouter } from 'next/router';

interface FormValues {
    fullname: string;
    email: string;
    password: string;
    image: string;
    address: string;
    phoneNumber: string;
    linkedln: string;
    twitter: string;
    facebook: string;
    instagram: string;
    website: string;
    bio: string;
    skills: string;
}

const validationSchema = yup.object().shape({
    fullname: yup.string().required('Name is required').min(10, 'Name must be at least 10 characters'),
    email: yup.string().email('Invalid email address').required('Email is required'),
    password: yup.string().min(8, 'Password must be at least 6 characters').required('Password is required').matches(
        /^(?=.*[A-Z])(?=.*[!@#$%^&*])(?=.*[0-9])(?=.*[a-z]).*$/,
        'Password must include capital letter, special character, and number'
    ),
});
const Signup: React.FC = () => {
    const [isLoading, setIsLoading] = useState(false);
    const [errors, setErrors] = useState<any>([]);
    const router = useRouter();
    
    const [formValues, setFormValues] = useState<FormValues>({
        fullname: '',
        email: '',
        password: '',
        image: '',
        address: '',
        phoneNumber: '',
        linkedln: '',
        twitter: '',
        facebook: '',
        instagram: '',
        website: '',
        bio: '',
        skills: '',
    });

    const handleInputChange = (event: React.ChangeEvent<HTMLInputElement>) => {
        const { name, value } = event.target;
        setFormValues((prevValues) => ({
            ...prevValues,
            [name]: value,
        }));
    };

    const handleSubmit = (e: React.FormEvent) => {
        e.preventDefault();
        setIsLoading(true); 
        validationSchema.validate(formValues, { abortEarly: false }).then(() => {
            axios.post("http://localhost:5000/user/signup", formValues).then((response: AxiosResponse) => {
                console.log(response.data);
                setFormValues({
                    fullname: '',
                    email: '',
                    password: '',
                    image: '',
                    address: '',
                    phoneNumber: '',
                    linkedln: '',
                    twitter: '',
                    facebook: '',
                    instagram: '',
                    website: '',
                    bio: '',
                    skills: '',
                });
                setErrors(response.data.message);
                router.push('/signin');
            })
            .catch((error) => {
                setErrors(error.message);
            })
            .finally(() => {
                setIsLoading(false);
            });
        }).catch((error) => {
            error.inner.forEach((error: { path: string; errors: any; }) => {
                if (error.path) {
                    errors[error.path] = error.errors;
                } else {
                    errors.general = error.errors;
                }
            })
            setIsLoading(false); 
        })
    }
    return (
        <>
            <Head>
                <title>Sign up</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
                crossOrigin="anonymous"
                ></link>
            </Head>
            <div className={styles.wrapper}>
                <div className="container-fluid">
                    <div className="row">
                        <div className="container col-md-6">
                            <div className={styles.form}>
                                <div className={styles.logo}>
                                    <Link href="/"><Image src={logo} alt="Logo" /></Link>
                                    <h1 >Create an account</h1>
                                    <p className={styles.txt}>Please filled all the required input fields.</p>
                                </div>
                                <form onSubmit={handleSubmit}>
                                    {errors && <p>{errors}</p>}
                                    <div className="form-group">
                                        <label className="form-label" htmlFor="fullname">Full name</label>
                                        <input type="text" className="form-control" name="fullname" id="fullname" placeholder="Full name" value={formValues.fullname} onChange={handleInputChange} />
                                        {errors.fullname && <div className=" text-danger">{errors.fullname}</div>}
                                    </div>
                                    <div className="form-group">
                                        <label className="form-label" htmlFor="email">Email</label>
                                        <input type="email" className="form-control" name="email" id="email" placeholder="Enter your email address" value={formValues.email} onChange={handleInputChange} />
                                        {errors.email && <div className=" text-danger">{errors.email}</div>}
                                    </div>
                                    <div className="form-group">
                                        <label htmlFor="password" className="form-label">Password</label>
                                        <input type="password" className="form-control" name="password" id="password" placeholder="&#42;&#42;&#42;&#42;&#42;&#42;&#42;&#42;" value={formValues.password} onChange={handleInputChange} />
                                        {errors.password && <div className=" text-danger">{errors.password}</div>}
                                        <Image src={eye} alt="" className={styles.image} />
                                    </div>
                                    <div className={styles.password}>
                                        <p>Password strength:</p>
                                        <p>Weak</p>
                                    </div>
                                    <Image src={strength} alt="Strength of thee password" />
                                    <div>
                                        <Image src={strong} alt="Strong password" />
                                        <span className={styles.txt}>Strong password must contain at least 8 characters, digits and uppercase letters.</span>
                                    </div>
                                    <div className={styles.signup}>
                                        <button type="submit" className="btn border-0 text-white" disabled={isLoading} >{isLoading ? "Signing up..." : "Sign Up"}</button>
                                    </div>
                                    <p className="text-center pt-2">Already have an account? <Link href="/signin" className={styles.login}>Log in</Link></p>
                                </form>
                            </div>
                        </div>
                        <div className="col-md-6">
                            <Image src={images} alt="" className={styles.images} />
                        </div>
                    </div>
                </div>
            </div>
        </>
    )}
export default Signup;