import * as React from 'react'
import Head from "next/head";
import Image from 'next/image'
import { useState } from "react";
import linkedIn from '../public/images/dashboard/linkedln.png';
import facebook from '../public/images/dashboard/facebook.png';
import twitter from '../public/images/dashboard/twitter.png';
import instagram from '../public/images/dashboard/instagram.png';
import share from '../public/images/dashboard/share.png';
import styles from '../styles/Ventures.module.scss';
import { fetchUser } from './features/users/userSlice';
import { useAppDispatch, useAppSelector } from './hooks';
import Nav from '../components/Nav';
import SideNav from '../components/SideNav';
import Link from 'next/link';

let email:any;
let token:any;
if (typeof window !== "undefined") {
    email = localStorage.getItem('email');
    token = localStorage.getItem('token');
}

const Ventures: React.FC = () => {
    const [isLoading, setIsLoading] = useState(false);
    const [errors, setErrors] = useState<any>([]);
    const dispatch = useAppDispatch();
    const user = useAppSelector(state => state.user.users);
    React.useEffect(() => {
        dispatch(fetchUser())
    }, [])
    if (!user) {
        return <div>Loading...</div>; // Display loading indicator while fetching user data
    }
    return (
        <>
            <Head>
                <title>Venture Profile</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
                crossOrigin="anonymous"
                ></link>
            </Head>
            <div className="container-fluid">
                <Nav />
                <SideNav />
                <div className={styles.section}>
                    <div className="row">
                        <div className="col-9">
                            <div className="d-flex justify-content-between px-3">
                                <h4>My Ventures</h4>
                                <div className={styles.section__info__text}>
                                    <Link href='ventures/add' className={`btn text-decoration px-3 py-2 btn-outline-${styles.clr}`}><i className="fa fa-plus" aria-hidden="true"></i> Add venture</Link>
                                </div>
                            </div>
                        </div>
                        <div className="col-3">
                            <div className={styles.section__session__body}>
                                <div className="">
                                    <div className="d-flex pb-4">
                                        <Image src={linkedIn} alt='Linkedln icon'/>
                                        <div className='ps-2'>
                                            <p className='mb-0'>Linkedln</p>
                                            <Link href='{user.linkedln}' className='text-decoration'>view likened profile</Link> <Image src={share} alt='share icon'/>
                                        </div>
                                    </div>
                                    <div className="d-flex pb-4">
                                        <Image src={twitter} alt='Twitter icon'/>                                               
                                        <div className='ps-2'>
                                            <p className='mb-0'>Twitter</p>
                                            <Link href='{user.twitter}' className='text-decoration'>view twitter profile</Link> <Image src={share} alt='share icon'/>
                                        </div>
                                    </div>
                                    <div className="d-flex pb-4">
                                        <Image src={instagram} alt='Instagram icon'/>
                                        <div className='ps-2'>
                                            <p className='mb-0'>Instagram</p>
                                            <Link href='{user.instagram}' className='text-decoration'>view instagram profile</Link> <Image src={share} alt='share icon'/>
                                        </div>
                                    </div>
                                    <div className="d-flex pb-2">
                                        <Image src={facebook} alt='Facebook icon'/>
                                        <div className='ps-2'>
                                            <p className='mb-0'>Facebook</p>
                                            <Link href='{user.facebook}' className='text-decoration'>view facebook profile</Link> <Image src={share} alt='share icon'/>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
export default Ventures;