/* eslint-disable @next/next/no-img-element */
import * as React from 'react'
import Head from "next/head";
import Image from 'next/image'
import { useState } from "react";
import styles from '../styles/Ventures.module.scss';
import phone from '../public/images/dashboard/call.png';
import website from '../public/images/dashboard/web.png';
import mail from '../public/images/dashboard/mail.png';
import { useDispatch, useSelector } from 'react-redux';
import { AppDispatch } from './redux/store';
import Nav from '../components/Nav';
import SideNav from '../components/SideNav';
import Link from 'next/link';
import axios from 'axios';
import axiosInstance from './features/axios';
import { fetchUser } from './redux/userSlide';
import { RootState } from './redux/store';
import { User } from './redux/types';

const Ventures: React.FC = () => {
    const [isLoading, setIsLoading] = useState(false);
    const [errors, setErrors] = useState<any>([]);
    const [data, setData] = useState<any>([]);
    const dispatch = useDispatch<AppDispatch>();
    const user = useSelector<RootState, User>((state) => state.user.users);
    const social = user.socials;
    React.useEffect(() => {
        dispatch(fetchUser());
        axiosInstance.get(`/ventures`).then((res) => {
            setData(res.data.data);
        }).catch((err) => {
            console.log(err)
        })
    }, [dispatch])
    // if (!user) {
    //     return <div>Loading...</div>;
    // }
    return (
        <>
            <Head>
                <title>Venture Profile</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
                <link
                href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
                rel="stylesheet"
                integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
                crossOrigin="anonymous"
                ></link>
            </Head>
            <div className="container-fluid">
                <Nav />
                <SideNav />
                <div className={styles.section}>
                    <div className="row">
                        <div className="col-md-9">
                            <div className="d-flex justify-content-between px-3 ">
                                <h4 className=''>My Ventures</h4>
                                <div className={styles.section__info__text}>
                                    <Link href='ventures/add' className={`btn text-decoration px-3 py-2 btn-outline-${styles.clr}`}><i className="fa fa-plus" aria-hidden="true"></i> Add venture</Link>
                                </div>
                            </div>
                            {/* <div className="row"> */}
                                {/* <div className="col-8"> */}
                                    <div className="row row-deck justify-content-around mt-5">
                                        {
                                            data.filter(function (venture:any) {
                                                return venture && venture.owner === user.id;
                                            }).map((item:any ,i: React.Key | null | undefined| number) => {
                                                return (
                                                        <div className="col-md-5" key={i}>
                                                            <Link href={`/ventures/${item.slug}`} className='text-decoration-none text-dark'>
                                                            <div className="card d-flex flex-column">
                                                                {item.banner ? <img className="card-img-top" src={item.banner} alt="" style={{height:"7rem"}}/> : <img className="card-img-top" src="https://via.placeholder.com/150" alt="" style={{height:"7rem"}}/>}
                                                                { item.logo?<img className="card-img-top" src={item.logo} alt="" style={{height:"4rem", width:"4rem", borderRadius: "0.5rem", position:"relative", top:"-2rem", left:"2rem"}}/> : <img className="card-img-top" src="https://via.placeholder.com/150" alt="" style={{height:"4rem", width:"4rem", borderRadius: "1rem", position:"relative", top:"-2rem", left:"2rem"}}/>}
                                                                <div className="card-body d-flex flex-column">
                                                                    <h3 className="card-title">{item.name}</h3>
                                                                    <div className="text-muted">{item.tagline}</div>
                                                                    <div className="d-flex align-items-center pt-4 mt-auto">
                                                                        <span className="avatar"></span>
                                                                        <div className="ms-3">
                                                                            <p className="text-body">{item.location}</p>
                                                                        </div>
                                                                    </div>
                                                                </div>
                                                            </div>
                                                        </Link>
                                                    </div>
                                                )
                                            })
                                        }
                                    </div>
                                {/* </div> */}
                            {/* </div> */}
                        </div>
                        <div className="col-md-3">
                            <div className="">
                                <div className={styles.profile}>
                                    <div className="shadows p-3">
                                        <div className=''>
                                            <div className={styles.section__session__header}>
                                                <h5>Contact Info</h5>
                                            </div>
                                            <div className={styles.section__session__body}>
                                                {
                                                    user.phone?
                                                    <div className="p-2 px-4">
                                                        <Image src={phone} alt='phone icon'/> <span className='text-dark ps-1'>Phone</span>
                                                        <div className="d-flex justify-content-between">
                                                            <p className='ps-4'> {user.phone ? user.phone : '(+234) 809 000 0000'} </p>
                                                        </div>
                                                    </div>:""
                                                }
                                                {
                                                    user.website?
                                                    <div className="p-2 px-4">
                                                        <Image src={website} alt='phone icon'/> <span className='text-dark ps-1'>Website</span>
                                                        <div className="d-flex justify-content-between">
                                                            <p className='ps-4'> {user.website ? user.website : 'samplewebsite.com'} </p>
                                                        </div>
                                                    </div>:""
                                                }
                                                {
                                                    user.email?
                                                    <div className="p-2 px-4 mb-3">
                                                                {/* <span><i className="fa-regular fa-envelope"></i></span> */}
                                                        <Image src={mail} alt='phone icon'/> <span className='text-dark ps-1'>Email address</span>
                                                        <div className="d-flex justify-content-between">
                                                            <p className='ps-4'> {user.email} </p>
                                                        </div>
                                                    </div>:""
                                                }
                                            </div>
                                        </div>
                                    </div>
                                    <div className="mt-2 shadows">
                                        <div className={styles.section__end}>
                                            <div className={styles.section__session__header}>
                                                <h5>Socials</h5>
                                            </div>
                                                <div className={styles.section__session__body}>
                                                    <div className="">
                                                        {
                                                            social.linkedin?
                                                            <div className='pb-4'>
                                                                <div className="d-flex">
                                                                        {/* <Image src={linkedIn} alt='Linkedln icon'/> */}
                                                                    <div className="text-white px-2 py-1 rounded-1" style={{
                                                                        backgroundColor: '#3B5998'
                                                                    }}>
                                                                        <i className="fa fa-linkedin" aria-hidden="true"></i>   
                                                                    </div>
                                                                    <div className='ps-3 pt-1'>
                                                                        <p className='mb-0'>LinkedIn</p>
                                                                    </div>
                                                                                
                                                                </div>
                                                                <Link href={social.linkedin.includes('https://')? `${social.linkedin}` :`https://${social.linkedin}`} className='text-decoration ps-5'>view likened profile <i className="fa-solid fa-arrow-up-right-from-square"></i></Link>
                                                            </div>
                                                            :""
                                                        }
                                                        {
                                                            social.twitter?
                                                            <div className='pb-4'>
                                                                <div className="d-flex">
                                                                        {/* <Image src={linkedIn} alt='Linkedln icon'/> */}
                                                                    <div className="text-white px-2 py-1 rounded-1 bg-info">
                                                                        <i className="fa fa-twitter" aria-hidden="true"></i>   
                                                                    </div>
                                                                    <div className='ps-3 pt-1'>
                                                                        <p className='mb-0'>Twitter</p>
                                                                    </div>
                                                                                
                                                                </div>
                                                                <Link href={social.twitter.includes('https://')? `${social.twitter}` :`https://${social.twitter}`}  className='text-decoration ps-5'>view twitter profile <i className="fa-solid fa-arrow-up-right-from-square"></i></Link> 
                                                            </div>
                                                            :""
                                                        }
                                                        {
                                                            social.instagram?
                                                            <div className='pb-4'>
                                                                <div className="d-flex">
                                                                        {/* <Image src={linkedIn} alt='Linkedln icon'/> */}
                                                                    <div className="text-white px-2 py-1 rounded-1" style={{
                                                                        background: 'radial-gradient(circle at 33% 100%, #fed373 4%, #f15245 30%, #d92e7f 62%, #9b36b7 85%, #515ecf)',
                                                                    }}>
                                                                        <i className="fa fa-instagram" aria-hidden="true"></i>   
                                                                    </div>
                                                                    <div className='ps-3 pt-1'>
                                                                        <p className='mb-0'>Instagram</p>
                                                                    </div>
                                                                        
                                                                </div>
                                                                <Link href={social.instagram.includes('https://')? `${social.instagram}` :`https://${social.instagram}`} className='text-decoration ps-5'>view instagram profile <i className="fa-solid fa-arrow-up-right-from-square"></i></Link>
                                                            </div>: ""
                                                        }
                                                        {
                                                            social.facebook?
                                                            <div className='pb-4'>
                                                                <div className="d-flex">
                                                                        {/* <Image src={linkedIn} alt='Linkedln icon'/> */}
                                                                    <div className="text-white px-2 py-1 rounded-1" style={{
                                                                        backgroundColor: '#3B5998'
                                                                    }}>
                                                                        <i className="fa fa-linkedin" aria-hidden="true"></i>   
                                                                    </div>
                                                                    <div className='ps-3 pt-1'>
                                                                        <p className='mb-0'>Facebook</p>
                                                                    </div>
                                                                        
                                                                </div>
                                                                <Link href={social.facebook.includes('https://')? `${social.facebook}` :`https://${social.facebook}`} className='text-decoration ps-5'>view facebook profile <i className="fa-solid fa-arrow-up-right-from-square"></i></Link>
                                                            </div>:""
                                                        }
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                        </div>
                    </div>
                </div>
            </div>
        </>
    )
}
export default Ventures;